version: "3.8"

services:
  mysql:
    image: mysql:8.4
    container_name: mysql_container
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: n3u3da!
      MYSQL_DATABASE: paymentprocessing

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql

    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$$MYSQL_ROOT_PASSWORD --silent || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 30s

    networks:
      - springboot-network

  springboot-app:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: springboot_container
    restart: on-failure

    depends_on:
      mysql:
        condition: service_healthy

    environment:
      DB_URL: jdbc:mysql://mysql:3306/paymentprocessing
      DB_USER: root
      DB_PASS: n3u3da!

    ports:
      - "8082:8080"

    networks:
      - springboot-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_container
    restart: on-failure
    depends_on:
      springboot-app:
        condition: service_started
    ports:
      - "8081:80"
    networks:
      - springboot-network
volumes:
  mysql-data:

networks:
  springboot-network: